### ISSUE TITLE
QNA

### ISSUE THREAD

**Issue by DarkFire98475** [Jackhammer9/Reddit-To-Instagram-Tutorial#1]
Can we run it on repl by installing instagrapi and others in console?
IF yes, whats the command to run the entire repl?

**Comment by DarkFire98475** [comment]
I have a problem while running the codes, It show:
 "All Posts Downloaded Sucessfully...
Uploaded image isn't in an allowed aspect ratio
Posted"
But it isnt actually posted...
Can u either bring a solution or update the code to filter subreddits with a custom ratio?

**Comment by Jackhammer9** [comment]
I’ll fix it printing “posted” even tho nothing is posted because of aspect ratio error anyways instagram supports very few aspect ratios but you can use the pillow library to resize these images before uploading making sure your image is uploaded the reason i didn't add this feature is because most of the times the image needs to be made larger resulting in significant quality loss.
